# Generated by Django 5.0.4 on 2024-04-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslist',
            name='businesses',
        ),
        migrations.AlterField(
            model_name='businesslist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='businesslist',
            name='businesses',
            field=models.ManyToManyField(to='scrapper.business'),
        ),
    ]
