# Generated by Django 5.0.4 on 2024-04-20 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_alter_businesslist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 17, 40, 38, 527976)),
        ),
        migrations.AddField(
            model_name='businesslist',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
