# Generated by Django 5.0.4 on 2024-04-21 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_businesslist_date_businesslist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslist',
            name='count_num',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='businesslist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 20, 18, 8, 15, 544920)),
        ),
    ]
