# Generated by Django 5.0.4 on 2024-04-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_alter_businesslist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslist',
            name='count_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesslist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 22, 11, 56, 27, 24244)),
        ),
    ]
